version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/dados.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped