"""adding the relationship between items in order tables

Revision ID: eaa43c9e19a5
Revises: b6c937ac5e2d
Create Date: 2025-08-16 18:53:34.213661

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "eaa43c9e19a5"
down_revision: Union[str, Sequence[str], None] = "b6c937ac5e2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
